### ISSUE TITLE
**Issue: Missing Image URLs in 'story' Folder `.parquet` Files**

### ISSUE THREAD

**Issue by hzphzp** [YeLuoSuiYou/openstorypp#1]
**I noticed the `.parquet` files in the 'story' folder are missing image URLs, which are crucial for my project. Could you please advise on how to access or prepare the data with these URLs included? Thank you!**

**Comment by YeLuoSuiYou** [comment]
> **I noticed the `.parquet` files in the 'story' folder are missing image URLs, which are crucial for my project. Could you please advise on how to access or prepare the data with these URLs included? Thank you!**

Thank you for following our work. For privacy reasons, sorry that we can not provide origin image with you, so you can download the original video first to get the frame. The code on how to download the video and organize the data can be viewed in the newly updated github readme, we privide two python script.

**Comment by hzphzp** [comment]
When I run the script, I got:
```bash
FileNotFoundError: Couldn't find a dataset script at /root/data/training_data/OpenstoryPlusPlus/story/story.py or any data file in the same directory.
```

**Comment by YeLuoSuiYou** [comment]
> When I run the script, I got:
> 
> ```shell
> FileNotFoundError: Couldn't find a dataset script at /root/data/training_data/OpenstoryPlusPlus/story/story.py or any data file in the same directory.
> ```

Hi, which script you run? you should run the python scripts in utilis to organize story dataset
